// =====================================================================
// ZITATE DATENBANK - Backstuben OS
// =====================================================================
// Hier werden alle Zitate für die Startseite zentral verwaltet.
// Füge neue Zitate einfach unten vor der letzten eckigen Klammer ein.
// Achte darauf, dass hinter jedem Zitat (außer dem letzten) ein Komma steht!

const QUOTES = [
    "Ohne Brot ist alles nichts.",
    "Wer früh aufsteht, hat das beste Brot.",
    "Die Nacht gehört denen, die für den Morgen backen.",
    "Der Duft frischer Brötchen macht die Nacht zum Tag.",
    "In der Stille der Nacht entsteht das Beste.",
    "Gutes Brot braucht Zeit – und einen wachen Bäcker.",
    "Frisches Brot ist die ehrlichste Arbeit der Welt.",
    "Jedes Brötchen beginnt als Idee in einer schlaflosen Nacht.",
    "Der Bäcker schläft, wenn andere frühstücken.",
    "Handwerk hat goldenen Boden – und goldene Kruste.",
    "Mehl, Wasser, Zeit – und ein Meister.",
    "Was des Nachts im Ofen liegt, beglückt den Morgen.",
    "Wenn die Stadt schläft, erwacht die Backstube.",
    "Der erste Biss am Morgen ist der Lohn der Nacht.",
    "Magie ist, wenn aus Mehl und Wasser ein Lächeln wird.",
    "Echte Handarbeit kennt keine Uhrzeit.",
    "Kaffee ist unser zweites Mehl.",
    "Ohne Kaffee keine Kruste.",
    "Der erste Kaffee ist für den Bäcker, der zweite für den Teig.",
    "Müdigkeit ist nur ein Mangel an Kaffee und Teig.",
    "Zuerst der Kaffee, dann die Brötchen.",
    "Wir bringen das Licht in den Morgen.",
    "Sterne leuchten am Himmel, unsere Brötchen im Ofen.",
    "Gegen 3 Uhr morgens wird aus Teig Charakter.",
    "Die beste Zeit des Tages beginnt im Dunkeln.",
    "Wenn die Eule schlafen geht, heizt der Bäcker den Ofen vor.",
    "Nachtschicht ist nur ein anderes Wort für Leidenschaft.",
    "Ein guter Teig vergisst nie, wer ihn geknetet hat.",
    "Wir backen keine Brötchen, wir backen den Morgen.",
    "Handwerk, das man schmecken kann.",
    "Jedes Korn hat eine Geschichte, wir backen das Happy End.",
    "Maschinen machen satt, Handwerk macht glücklich.",
    "Brot ist die Seele der Bäckerei.",
    "Geduld ist die wichtigste Zutat.",
    "Wer den Teig nicht ehrt, ist des Brotes nicht wert.",
    "Perfektion braucht keine Sonne, nur einen heißen Ofen.",
    "Ich bin nicht nachtaktiv, ich bin bäckeraktiv.",
    "Teigflüsterer im Nachtdienst.",
    "Krümelmonster arbeiten hier nicht, wir backen sie.",
    "Wer krümelt, hat mehr vom Brot.",
    "Wir haben den Teig, der die Welt bedeutet.",
    "Ich kenne 50 Shades of Brown – alle aus dem Ofen.",
    "Leg dich nicht mit dem Bäcker an, er hat die heißesten Öfen.",
    "Frühaufsteher? Wir sind gar nicht erst ins Bett gegangen.",
    "Mein Workout ist Teig kneten.",
    "Wir sind die wahren Herrscher der Hefe.",
    "Wir machen das Frühstück erst möglich.",
    "Dein Lächeln am Morgen ist unser Schweiß in der Nacht.",
    "Ein Morgen ohne unser Brot ist nur ein halber Tag.",
    "Wir wecken die Stadt mit Duft.",
    "Backen ist Liebe, die man essen kann.",
    "Der Tag wird gut, wenn das Brot knuspert.",
    "Mehlstaub ist das Glitzer der Bäckerei.",
    "Hefe schläft nie, und wir auch nicht.",
    "Ein Tag ohne Mehl an den Händen ist ein verlorener Tag.",
    "Die wahre Magie passiert zwischen 2 und 5 Uhr morgens.",
    "Wir machen den Teig, der die Träume weckt.",
    "Knusprig von außen, weich von innen – wie ein guter Bäcker.",
    "Backen: Die Kunst, Mehl in Gold zu verwandeln.",
    "Früher Vogel fängt den Wurm. Der Bäcker überfährt ihn auf dem Weg zur Arbeit.",
    "Wer morgens frisch aussieht, hat nachts nicht gebacken.",
    "Mein Augenring-Level: Bäckermeister.",
    "Tageslicht wird völlig überbewertet.",
    "Ich backe keine Brötchen, ich verarbeite meine Aggressionen in Teig.",
    "Lächle. Du kannst sie nicht alle in den Ofen schieben.",
    "Wir weinen nicht, das ist nur Mehlstaub im Auge.",
    "Schlafen ist für Leute, die den Ofen nicht bedienen können.",
    "Wenn du wüsstest, wie viel Hass in diesem Croissant steckt, würdest du es langsamer essen.",
    "Brot macht nicht dick. Deine fehlende Disziplin macht dick.",
    "Das einzige, was hier aufgeht, ist der Teig. Meine Laune sicher nicht.",
    "Ich bin nicht zynisch. Ich arbeite nur seit 2 Uhr nachts.",
    "Natürlich ist das Handarbeit. Die Maschinen haben sich geweigert.",
    "Ein guter Bäcker braucht keinen Schlaf, nur mehr Kaffee und Verzweiflung.",
    "Wer behauptet, Backen sei entspannend, hat noch nie unter Zeitdruck gestanden.",
    "Verbrannt ist es erst, wenn der Rauchmelder singt. Vorher ist es Röstaroma.",
    "Die Hefe arbeitet. Ich funktioniere nur noch.",
    "Kaffee: Weil Mord in der Backstube eine Sauerei macht.",
    "Wir kneten den Teig, bis er so weich ist wie die Ausreden der Frühschicht.",
    "Jeder will frisches Brot, aber niemand will um 3 Uhr aufstehen.",
    "Ich habe heute schon mehr geleistet als du in deiner gesamten Woche. Guten Morgen.",
    "Mein Therapeut ist aus Edelstahl und backt bei 220 Grad.",
    "Du nennst es Artisan, ich nenne es Pech beim Formen.",
    "Mit Liebe gebacken heißt eigentlich unter massivem Schlafmangel zusammengeschustert.",
    "Wir sind hier nicht bei Wünsch-dir-was, wir sind in der Backstube.",
    "Wer nicht spurt, wird eingemehlt und mitgebacken.",
    "Nachtschicht: Die Kunst, wach zu bleiben, während die Welt schläft und nervt.",
    "Natürlich habe ich gute Laune. Sie ist nur sehr gut versteckt. Unter dem Mehl.",
    "Der Kunde ist König. Aber der Bäcker ist der Diktator am Ofen.",
    "Das Geheimnis eines guten Brotes? Zorn. Viel Zorn beim Kneten.",
    "Wenn Blicke backen könnten, bräuchten wir keinen Ofen mehr.",
    "Ich brauche keine Sonne, ich verbrenne mich jeden Tag am Blech.",
    "Manchmal frage ich mich, ob der Teig mich auch kneten will.",
    "Ich habe einen Traum: 8 Stunden Schlaf am Stück. Verrückt, oder?",
    "Mehl ist mein Make-up.",
    "Das Geheimnis unserer Brötchen? Wir verraten es dir nicht.",
    "Bäcker: Der einzige Beruf, wo man dafür bezahlt wird, nachts Krach zu machen.",
    "Sauerteig ist wie ein Haustier. Man muss ihn füttern und pflegen.",
    "Ich habe heute wieder Bleche gestemmt. Fitnessstudio abgemeldet.",
    "Wenn du mich vor 6 Uhr ansprichst, übernimmst du die volle Verantwortung.",
    "Die Hefe ist heute motivierter als ich.",
    "Wir backen nicht, um reich zu werden. Wir backen, weil wir nicht anders können.",
    "Mein Schlafrhythmus ist eine urbane Legende.",
    "Guten Morgen? Für mich ist es gefühlt Dienstagabend.",
    "Wenn Vampire Bäcker wären, hätten sie bessere Arbeitszeiten.",
    "Tageslicht verbrennt meine Haut. Ofenlicht wärmt meine Seele.",
    "Müdigkeit ist eine Illusion. Mehlstaub ist real.",
    "Schlafen ist der kleine Bruder von 'Teig ruhen lassen'.",
    "Die Vögel zwitschern. Zeit, sie geistig zu erwürgen.",
    "Mein Bett hat heute eine Vermisstenanzeige aufgegeben.",
    "Wer mir nachts um 2 fröhlich 'Guten Morgen' wünscht, wird im Kneter versenkt.",
    "Wie ich die Nachtschicht überlebe? Hass und Hefe.",
    "Meine Augenringe haben eigene Postleitzahlen.",
    "Gähnen ist der stumme Schrei nach einem Croissant.",
    "Wir sind wie Batman. Nur mit Schürze und Brötchen.",
    "»Du siehst müde aus.« – »Ich bin Bäcker, das ist mein Gesicht!«",
    "Im nächsten Leben werde ich Murmeltier. Oder Beamter.",
    "Wer nachts weint, muss morgens den Teig weniger salzen.",
    "Ich bin nicht nachtragend, ich bin nacht-knetend.",
    "Ein echter Bäcker fürchtet nicht die Dunkelheit, sondern den leeren Kaffeesack.",
    "Meine Blutgruppe ist K- (Kaffee, negativ eingestellt).",
    "Vor dem ersten Kaffee ist Teig formen ein gefährliches Unterfangen.",
    "Bäckerwasser: 50% Arabica, 50% Robusta.",
    "Ohne Kaffee backe ich nur Fladenbrot. Aus Prinzip.",
    "Ein Bäcker ohne Kaffee ist wie ein Ofen ohne Strom.",
    "Gib mir Kaffee und niemand wird verletzt.",
    "Entkoffeinierter Kaffee ist wie glutenfreies Mehl: Sinnlos.",
    "Die Kaffeemaschine ist der heimliche Chef der Backstube.",
    "Mein Ruhepuls ist ein doppelter Espresso.",
    "»Wie viel Kaffee trinkst du in der Schicht?« – »Ja.«",
    "Ich atme Mehl und blute Espresso.",
    "Kaffee rein, Magie raus.",
    "»Haben Sie was Veganes?« – »Ja, das Wechselgeld.«",
    "»Sind die Brötchen von heute?« – »Nein, von morgen. Ich bin meiner Zeit voraus.«",
    "Wir backen mit Liebe. Und wenn die alle ist, nehmen wir Sarkasmus.",
    "Wer den Rand vom Kuchen abschneidet, hat die Kontrolle über sein Leben verloren.",
    "Ich backe, also fluche ich.",
    "Mein Geduldsfaden ist kürzer als eine Baguette-Spitze.",
    "Kunde: »Ich hätte gern ein warmes Brot.« Ich: »Dann legen Sie sich drauf.«",
    "Wenn Dummheit quietschen würde, müsste ich den Laden nachts mit Ohropax betreten.",
    "Wenn der Teig reißt, reißt mir der Geduldsfaden.",
    "Ein Brötchen, das auf den Boden fällt, nennt man »Azubi-Frühstück«.",
    "Das ist kein Loch im Brot, das ist Luft-Design. Kostet eigentlich extra.",
    "Ich bin Bäcker, kein Zauberer. Das Schwarzbrot wird nicht heller.",
    "Wer zu spät kommt, isst die Reste.",
    "»Ich will aber die ganz dunklen.« *gibt verbrannte Brötchen* »Oh, die sind mir zu dunkel.«",
    "Ich habe es mit Liebe gebacken. Das muss als Entschuldigung für die Form reichen.",
    "»Machen Sie auch Torten?« – »Nur wenn ich jemanden bestrafen will.«",
    "Die besten Kunden wissen, was sie wollen, BEVOR sie den Laden betreten.",
    "Ein Tag ohne nervige Sonderwünsche ist wie ein Brot ohne Salz: fade.",
    "Bäcker-Regel Nr. 1: Fass mein Messer nicht an. Regel Nr. 2: Fass mein Blech nicht an!",
    "Mehl ist der Staub, aus dem die Träume sind.",
    "Ein gutes Brot spricht für sich selbst.",
    "Wir formen nicht nur Teig, wir formen Erinnerungen.",
    "Jedes Brot ist ein Unikat. Genau wie meine Brandblasen.",
    "Wenn Mehl in der Luft tanzt, ist die Welt für einen Moment still.",
    "Hefe ist ein Lebewesen. Und manchmal zickt sie wie eine Diva.",
    "Ein Laib Brot ist die ehrlichste Währung der Welt.",
    "Wer mit den Händen arbeitet, backt mit dem Herzen.",
    "Wahre Schönheit kommt von innen. Und hat eine verdammt knusprige Kruste.",
    "Sauerteig braucht Liebe, Zeit und gelegentliche Beschimpfungen.",
    "Kein Parfüm der Welt riecht besser als frisches Brot.",
    "Ein Bäcker misst die Zeit nicht in Stunden, sondern in Gehzeiten.",
    "Backen ist die schönste Form der Alchemie.",
    "Im Teig spiegelt sich die Seele des Bäckers. (Deshalb ist meiner heute mürrisch).",
    "Brötchen sind wie kleine, essbare Umarmungen.",
    "Handwerk lässt sich nicht durch Knopfdruck ersetzen.",
    "Gute Kruste, guter Kern.",
    "Das einzige, was hier morgens knuspert, sind meine Gelenke.",
    "Wer behauptet, Maschinen machen alles besser, hat noch nie ein handgeformtes Croissant gegessen.",
    "Der Timer des Ofens ist der Herzschlag der Backstube.",
    "Verbrennungen 1. Grades sind unser Initiationsritus.",
    "Hefe verzeiht nicht. Hefe erinnert sich.",
    "Es heißt »Bäcker« und nicht »Geduldsengel«.",
    "Ich lebe in einer Welt aus 220 Grad.",
    "Staublunge? Nein, Mehl-Aura!",
    "Bäcker arbeiten nicht, sie zelebrieren das Grundbedürfnis.",
    "50 kg Mehl heben ersetzt jeden Therapeuten.",
    "Backen ist wie Tetris: Am Ende muss alles aufs Blech passen.",
    "Wer »nur mal kurz reinschaut«, muss fegen.",
    "Jeder Ofen hat seine eigene Persönlichkeit. Meiner ist ein sturer Esel.",
    "Was in der Backstube passiert, bleibt in der Backstube. Außer dem Brot.",
    "Die gefährlichste Waffe des Bäckers? Ein heißes Blech im falschen Moment.",
    "Ein Bäcker weint nicht, sein Teig war nur zu feucht.",
    "Wenn der Teig klebt, klebt der ganze Tag.",
    "Mein Ofen hat mehr Ausstrahlung als manche Leute.",
    "Ich bin heute völlig durch den Wind... ähm, Teig.",
    "Lass uns die Krumen zusammenkratzen und das Beste draus machen.",
    "Wir backen das schon!",
    "Komm auf die dunkle Seite. Wir haben Schwarzbrot.",
    "Du gehst mir tierisch auf den Keks!",
    "Kneten ist mein Cardio.",
    "Ein Bäcker ist immer auf Zack, denn er hat den Teig im Nacken."
,
    "BäckereiOS: Entwickelt von einem Bäcker mit Ideen und einer KI mit zu viel Kaffee im System.",
    "Manche Menschen debuggen Code. Ich debugge Bleche.",
    "const frosterDone = true; // Spoiler: war es nicht.",
    "Wir nennen es 'unerwartetes Verhalten'. Der Fachmann nennt es Bug.",
    "Die App läuft. Der Bäcker auch. Nur in die entgegengesetzte Richtung.",
    "Froster-Status: undefined. Genau wie mein Schlaf.",
    "Ich wollte nur kurz was ändern. Drei Stunden später...",
    "Kein stiller Architekturwandel. Außer wenn's brennt.",
    "Logic before elegance. Mehl before Maschine.",
    "Der Service Worker hat mal wieder seinen eigenen Kopf.",
    "Cache geleert, Seele gerettet.",
    "Wenn der Ofen läuft und die App auch, ist die Welt in Ordnung.",
    "Ein Commit um 4 Uhr morgens enthält immer Wahrheit.",
    "Pull Request: Bitte. Merge: Danke. Fehler danach: Natürlich.",
    "Die Fehlmenge ist kein Bug, sie ist ein Feature der Realität.",
    "Wir haben darüber diskutiert. Dann haben wir nochmal diskutiert. Dann hat der Teig entschieden.",
    "Dokumentation ist wie Salz im Brot: Man merkt es erst, wenn es fehlt.",
    "Version 15 ist nicht die fünfzehnte Version. Sie ist die erste, die hält.",
    "Der Closure-Bug bei Mohnschnecken bleibt für immer in unserer Seele.",
    "Manchmal knetet man den Teig. Manchmal knetet der Teig einen.",
    "Wenn du nicht weißt, was du brauchst, um dein Ziel zu erreichen, fragst du die KI. Wenn die KI es nicht weiß, fragt sie zurück.",
    "Gute Nacht! Guten Morgen? Beides gleichzeitig, irgendwie.",
    "Nachtschicht-Regel Nr. 1: Froster prüfen. Nachtschicht-Regel Nr. 2: Nochmal prüfen.",
    "Unsere App schläft nicht. Wir auch nicht. Das ist kein Zufall.",
    "Wer den Teig versteht, versteht die Nachtschicht. Wer die Nachtschicht versteht, versteht alles."

];